### ISSUE TITLE
Didn't thought this will ever exist lmao

### ISSUE THREAD

**Issue by SolsticeSpectrum** [BleachDev/bleachhack-legacy#1]
But is it safe from log4shell? Kappa

**Comment by BleachDev** [comment]
https://github.com/BleachDrinker420/bleachhack-legacy/blob/4144b72df5d0a444d9dde4ac75e5f1fcd20600cc/build.gradle#L45-L46

**Comment by SolsticeSpectrum** [comment]
Oh cool
